### ISSUE TITLE
Make tables more conventional

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#1]
1. Create good primary keys for all of our tables except for Customers.  The Customers.[Customer ID] matches with another database.
2. Change all field names in each table to be in a unified format.  Choose a convention and stick with it.  For example camelCase may be the best way _(for example Customer ID might become customerID, Email Address might become emailAddress, User Type might become userType)_.  Change all of the fields in all of the tables so that they are the same style.  Use your own experience to see what style is the best for this.
3. Check all forms, reports, and queries to make certain that they did not break when we renamed things in the tables.

**Comment by smsu07** [comment]
Sorry I changed the Customer ID to Cust_ID but [Customer ID] is intake so you can use it

**Comment by sdaigle2** [comment]
It's ok.  We'll deal with it.  Just commit the code when you are ready.

**Comment by smsu07** [comment]
OK, Will do. Still working on the changes.

**Comment by smsu07** [comment]
Done, Please Check.

**Comment by sdaigle2** [comment]
These seem good.
