### ISSUE TITLE
Create a function called mergeCustomer(custID1, custID2) 

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#11]
Create a function called **mergeCustomer(custID1, custID2)** that does the following:

1. receives two arguments: **custID1** is the primary key of a customer, **custID2** is the primary key of another customer.
2. check to see if **custID1** and **custID2** exist, if yes, continue
3. check to see if **custID1** == **custID2** if yes, stop.
4. Searches through the Jobs table for **custID2**. Every instance of **custID2** in Cust_ID of any Jobs entry changes to **custID1**
5. Deletes **custID2** from the Customers table
6. returns 1 for success, or 0 for fail

**Comment by smsu07** [comment]
Completed, Please test.

**Comment by sdaigle2** [comment]
Works well.  Good job.

**Comment by sdaigle2** [comment]
I noticed a bug.  Please work on this.  Here's how to reproduce it:

1. Create a customer called **test-1**
2. Create a customer called **test-2**
3. Do not create any jobs associated with either customer. 
4. Attempt to merge **test-1** and **test-2.**
5. Check the Customers table and notice that **test-1** and **test-2** still exist.  This is bad.  **test-2** should be gone.
6. Create a job called **test-job-1** linked to the customer **test-1**
7. Create a job called **test-job-2** linked to the customer **test-1**
8. Attempt to merge **test-1** and **test-2**
9. Check the Customers table and notice that **test-2** is gone.  This is good.  It should work like this in step 5 of this example.

**Comment by smsu07** [comment]
Applied the changes as requested

**Comment by sdaigle2** [comment]
Looks good.  Closing Issue.
