### ISSUE TITLE
implement mergeJob( jobID1, jobID2)

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#13]
1. in **frmJobs**, create a new button that says **Merge**
2. When you click the **Merge** button, an new modal form called **frmMergeJobs** comes up
3. **frmMergeJobs** has two Combo Boxes and a button that says Merge
4. Both combo boxes will display all **Job_Name** entries from the **Jobs** table
5. the first combo box will be pre-loaded with the **Job_Name** selected in the **frmJobs** form
6. the users will enter the **Job_Name** in the second combo box.
7. When the user clicks Merge, the code will call **mergeJobs(jobID1, jobID2)** and **frmMergeJobs** will close.

**Comment by smsu07** [comment]
What I understood-

**Comment by smsu07** [comment]
completed & Uploaded to Github, Please check.

**Comment by sdaigle2** [comment]
It works well.  I would like to make one change to the functionality:
## Current functionality
User clicks **btnMerge** in **frmJobs**
```
Private Sub btnMerge_Click()
If (IsNull(txtJobID) Or txtJobID = "") Or (IsNull(txtJobName) Or txtJobName = "") Then
    MsgBox "Please select/Create a Job First", vbInformation, "Select Job"
    Exit Sub
End If
DoCmd.OpenForm "frmMergeJobs", acNormal, , , , , txtJobID
End Sub
```

## Desired functionality
User clicks **btnMerge** in **frmJobs**
```
Private Sub btnMerge_Click()
If (IsNull(txtJobID) Or txtJobID = "") Or (IsNull(txtJobName) Or txtJobName = "") Then
    'open frmMergeJobs with nothing in either Combo Box
End If
DoCmd.OpenForm "frmMergeJobs", acNormal, , , , , txtJobID
End Sub
```

**Comment by smsu07** [comment]
Changed Accordingly and Uploaded to GitHub.

**Comment by sdaigle2** [comment]
Good job. Closing issue.
