### ISSUE TITLE
Quickadd Jobs

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#15]
In **frmHoursLogOverHead** **cmbJob** and **frmCreateTask** **cboJobID**, users often times try to type names of jobs that are not yet in the database.  They are trying to create new jobs.  Other programs have a nice _Quick Add_ feature that  is very useful.  Here's how it should work:

 If the user types something that is not a valid entry in **cmbJob /  cboJobID**, they should not see the standard VBA error.  Instead, this should happen:

1. Check to see if the selection in **cboCustomer / cmbCustomer** is in the **Customers** table.  If no, display a message that says "Please select a valid Customer before selecting a job." and delete the user entry in **cmbJob /  cboJobID**.  If yes, continue
2. A message box should appear that says, "The job name: " & cmbJob /  cboJobID.value & " is not yet created for the customer: " & cboCustomer / cmbCustomer.value & ".  Would you like to quick add it?" (Yes) or (No).  If user selects No, then stop,  If the user selects Yes, then continue
5. Create a new Job in the **Jobs**  table with the the following information:
```
Job_ID 'is autogenerated
Job_Name = cmbJob /  cboJobID.value
Job_Description = ""
Cust_ID = 'the Cust_ID of the customer shown in cboCustomer / cmbCustomer
Cust_ID_OLD = "PDI"
jobStatus = "In progress"
```

**Comment by smsu07** [comment]
I am a bit confused about the task scope.
I have completed for the form frmHoursLogOverHead but not clear about the frmCreateTask .
Will be good if we can discuss on that today at 09:00 PM my time(GMT+6)

**Comment by sdaigle2** [comment]
I'm guessing that the confusion is coming from the fact that it is not clear how to use **frmCreateTask** as a developer.  It get's pre-populated when other forms load it.  Here's how to use it as a regular user:

1. open **frmMainMenu**
2. Click the **Task Lists - Tooling** Button
3. Click the **Create New Task** Button
The Job ID combo box in **frmCreateTask** should work just like the one that you created in **frmHoursLogOverhead**

Before you do this, please make a change to what you did in **frmHoursLogOverhead**.   The quick-add feature works very well, except for 1 instance.  

> 1.) Check to see if the selection in cboCustomer / cmbCustomer is in the Customers table. If no, display a message that says "Please select a valid Customer before selecting a job." and delete the user entry in cmbJob / cboJobID. If yes, continue

**Comment by smsu07** [comment]
Please check

**Comment by sdaigle2** [comment]
Checked.  Everything seams to work nicely.
