### ISSUE TITLE
Make the styles uniform for all reports in the database. 

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#2]
I like the style of frmMainMenu.  Please make all forms and reports look similar to it.  

1.) All forms should have a heading that says:
- Form title
- Current User
- Anything else relevant like the current date.

2.) All forms should have a back button in the same place and it should always be gray.

**Comment by smsu07** [comment]
Done, Please Check.

**Comment by sdaigle2** [comment]
Looks good.
