### ISSUE TITLE
Changes to frmHoursLogOverhead

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#5]
Your user interface allows a user to edit hours records, and occasionally log new hours records. I want the interface to allow the user to log new hours, and occasionally edit an existing record. For that reason, I would like you to make the following changes.

**Design issues:**
- When the form opens, it has you start editing a record.  I would like it to have you start creating a new record.   The user should be able to stop creating a new record by clicking a record in the data table, by clicking the next or previous buttons, or clicking Cancel.
- Once you save a record, it should default to creating a new record.
- It should not let you create or save record without having the Date, Weekday, Employee Name, Customer Name, Job ID, Phase, and Time Spent.  Description is optional.  If the user tries to save changes without 
- When the form loads, cmbEmployee should be prefilled by the current use who is logged in.  This is stored in a global variable called glblCurrentUser
- The data table at the bottom of the form should only show hours for the employee selected in cmbEmployee between startDate and endDate.  If no employee is selected in cmbEmployee, then it should show nothing.
- The information in the text box called "Time Spent" should be rounded to the nearest quarter hour.   _Example, if the user enters "1.3" it should be changed to 1.25.  If the user enters "1.49" it should be changed to 1.5.  If the user enters "1", it should be left as "1"_ 
- The information in the text box called "Time Spent" should be checked for negative values, and set to 0 if a negative is entered.

**Bugs**
- When the user changes what is in cmbCustomer, all of the records displayed in the data table get changed too.
- While editing a record, the save button does nothing.

**Comment by smsu07** [comment]
Completed and updated to GitHub, Please check.

**Comment by sdaigle2** [comment]
The changes look good.   Good job navigating my complex request.  I've added a few style changes to this.  Please pull my most recent commit: cc3b8f8379e8b03cfb3b0850838952f51771ae7b and then make a few more changes:

- cmbEmployee.  You made it so this is filled by glblCurrentUser.  That is good.  However, the user should also be able to change and edit another user's information.  When cmbEmployee is updated, the rest of the form should refresh.
- Customer should be displayed in the data table at the bottom of the form.

Once complete, commit and push your changes, and then continue to the other tasks.

**Comment by smsu07** [comment]
Completed the Employee Change task and displayed the Customer in the data table, Please Check.
