### ISSUE TITLE
Changes for frmJobs

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#6]
Your user interface allows a user to Edit Jobs, and occasionally Create a New Job.  I want the interface to allow the user to Create New Jobs, and occasionally edit an existing job.  For that reason, I would like you to make the following changes.

- The data table at the bottom of this sheet should show only the jobs associated with the customer in cmbCustID.
- The user should not see Job_ID.  The user doesn't need to know what the Job_ID is.  If it's the primary key, the use should never have the opportunity to touch Job_ID.
- When the form opens, it should be in create-job mode.  If the user clicks on one of the other jobs in the data table, clicks cancel, or clicks the next/previous arrows, it should go back to edit-job mode.
- When the user creates a new job, the form should stay in edit-job mode.

**Steps to reproduce a serious bug:**
Click New
Click Back
See VBA errors

**Comment by sdaigle2** [comment]
In addition to the changes above, please spend some time getting familiar with frmHoursLogOverhead.  I made some extra changes to that where buttons hide when they are not needed.  Please make this form work like that.

**Comment by smsu07** [comment]
Completed, Please Check.
