### ISSUE TITLE
Changes for frmCustomers

### ISSUE THREAD

**Issue by sdaigle2** [sdaigle2/pdi-database#7]
Your user interface allows a user to Edit Customers, and occasionally Create a New Customer. I want the interface to allow the user to Create New Customers, and occasionally edit an existing Customer. For that reason, I would like you to make the following changes.

- The user should not see Customer_ID. The user doesn't need to know what the Customer_ID is. If it's the primary key, the use should never have the opportunity to touch Customer_ID.
- When the form opens, it should be in create-customer mode. If the user clicks on one of the other jobs in the data table, clicks cancel, or clicks the next/previous arrows, it should go back to edit-customer mode.
- When the user creates a new customer, the form should stay in create-customer mode, but clear the Customer Code, Customer Name, and Customer Type fields.

**Steps to reproduce a serious bug:**
Click New
Click Back
See VBA errors

**Comment by smsu07** [comment]
Will I start now?

**Comment by sdaigle2** [comment]
In addition to the changes above, please spend some time getting familiar with frmHoursLogOverhead.  I made some extra changes to that where buttons hide when they are not needed.  Please make this form work like that.

**Comment by smsu07** [comment]
Completed,
